-- Create temporary table for importing CSV data
-- We use TEXT for dates to avoid errors during CSV upload due to format differences (DD/MM/YYYY vs YYYY-MM-DD).
-- We will cast them to dates in the final insert query.

CREATE TABLE temp_import_caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caixa_id BIGINT,
    valor NUMERIC(15,2),
    operacao TEXT,
    clientes_id BIGINT,
    data_lancamento TEXT, -- Use TEXT to handle 'DD/MM/YYYY HH:mm' safely
    detalhes TEXT,
    compromisso_id BIGINT,
    especie TEXT,
    historico TEXT,
    ano_mes_referencia TEXT,
    data_vencimento TEXT, -- Use TEXT to handle 'DD/MM/YYYY' safely
    grupo_compromisso_id BIGINT
);

COMMENT ON TABLE temp_import_caixa IS 'Tabela temporária para importação de dados legados via CSV';
